version: "2"
volumes:
    uhura-volume:
    fastdds-volume:

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    command: "--cluster_name NATS -c nats-server.conf --cluster nats://0.0.0.0:6222 --http_port 8222"
  uhura_core:
    #image: patonz/uhura:core_0.1.33-test
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
      - DEBUG=true
    depends_on:
      - nats
  uhura_adapter:
    #image: patonz/uhura:adapter_nats_0.1.33-test
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
      - DEBUG=true
    depends_on:
      - uhura_core_a
      - nats





    

