version: "2"
volumes:
    uhura-volume:
    fastdds-volume:
    test-wifi:
      external: true

services:
  nats-netrob:
    image: nats
    ports:
      - "192.168.50.186:8222:8222"
      - "192.168.50.186:4222:4222"
      - "192.168.50.186:6222:6222"
    command: "--cluster_name NATS-NETROB -c nats-server.conf --cluster nats://0.0.0.0:6222 --routes=nats://192.168.50.75:6222"

  nats-mobile:
    image: nats
    ports:
      - "192.168.1.70:9222:8222"
      - "192.168.1.70:5222:4222"
      - "192.168.1.70:7222:6222"
    command: "--cluster_name NATS-MOBILE -c nats-server.conf --cluster nats://0.0.0.0:6222 --routes=nats://192.168.1.99:7222"
    depends_on:
      - nats-netrob

  uhura_core:
    #image: patonz/uhura:core_0.1.33-test
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - NATS_SERVER_ADDRESS=nats://192.168.50.187:4222
      - ID=BLOOD
      - DEBUG=true
      - CADENCE=2000
    volumes:
      - ${PWD}/data:/app/
    depends_on:
      - nats-netrob
  uhura_adapter_netrob:
    #image: patonz/uhura:adapter_nats_0.1.33-test
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - NATS_SERVER_ADDRESS=nats://192.168.50.186:4222
      - ADAPTER_NATS_SERVER_ADDRESS=nats://192.168.50.187:4222
      - ADAPTER_TYPE=nats_netrob
      - ID=BLOOD
      - DEBUG=true
    depends_on:
      - uhura_core
      - nats-netrob
  uhura_adapter_mobile:
        #image: patonz/uhura:adapter_nats_0.1.33-test
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - NATS_SERVER_ADDRESS=nats://192.168.50.186:4222
      - ADAPTER_NATS_SERVER_ADDRESS=nats://192.168.1.70:5222
      - ADAPTER_TYPE=nats_mobile
      - ID=BLOOD
      - DEBUG=true
    depends_on:
      - uhura_core
      - nats-mobile






    

