version: "2"
volumes:
    uhura-volume:

services:
  uhura_gateway:
    #image: patonz/uhura:gateway_${TAG}
    build: 
      context: .
      dockerfile: gateway.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=${UHURA_CORE_ID}
    depends_on:
      - uhura_adapter_a
      - nats
  uhura_discovery_a:
    #image: patonz/uhura:discovery_${TAG}
    build: 
      context: .
      dockerfile: discovery.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=${UHURA_CORE_ID}
      - SYNC_DELAY=${SYNC_DELAY}
      - TEST=true
      - MAX_NODES=${MAX_NODES}
      - NODES=${NODES}
    volumes:
      - uhura-volume:/test_results

    depends_on:
      - uhura_gateway_a
      - nats
  uhura_core_a:
    #image: patonz/uhura:core_${TAG}
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=${UHURA_CORE_ID}
      - DEBUG=false
    depends_on:
      - nats
  uhura_adapter:
    #image: patonz/uhura:adapter_nats_${TAG}
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=${UHURA_CORE_ID}
      - DEBUG=false
    depends_on:
      - uhura_core_a
      - nats