version: "2"
volumes:
    uhura-volume:
    fastdds-volume:
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  uhura-core-a:
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
  uhura-adapter-a:
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
  uhura-core-b:
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=BETA
  uhura-adapter-b:
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=BETA
  #clientjs:
  #  build: ./client
  #  network_mode: host
  #  command: "tail -f /dev/null"
  #uhura:
  #  build: 
  #    dockerfile: test.Dockerfile
  #    context: .
  #  volumes:
  #    - 'uhura-volume:/data'
  #  network_mode: host
  #  privileged: true
  #  #command: "tail -f /dev/null"
  #  command: node test.js
    

