version: "2"
volumes:
    uhura-volume:
    fastdds-volume:

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS -c nats-server.conf --cluster nats://0.0.0.0:6222 --http_port 8222"
    volumes:
      - $PWD/nats-server.conf:/nats-server.conf

  uhura-gateway-a:
    image: patonz/uhura:gateway_${TAG}
    build: 
      context: .
      dockerfile: gateway.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=ALPHA
    depends_on:
      - uhura-adapter-a
      - nats
  uhura-discovery-a:
    image: patonz/uhura:discovery_${TAG}
    build: 
      context: .
      dockerfile: discovery.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=ALPHA
    depends_on:
      - uhura-gateway-a
      - nats
  uhura-core-a:
    image: patonz/uhura:core_${TAG}
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
      - DEBUG=false
    depends_on:
      - nats
  uhura-adapter-a:
    image: patonz/uhura:adapter_nats_${TAG}
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
      - DEBUG=false
    depends_on:
      - uhura-core-a
      - nats



  uhura-gateway-b:
    image: patonz/uhura:gateway_${TAG}
    build: 
      context: .
      dockerfile: gateway.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=BETA
    depends_on:
      - uhura-adapter-b
      - nats
  uhura-discovery-b:
    image: patonz/uhura:discovery_${TAG}
    build: 
      context: .
      dockerfile: discovery.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=BETA
    depends_on:
      - uhura-gateway-b
      - nats
  uhura-core-b:
    image: patonz/uhura:core_${TAG}
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=BETA
      - DEBUG=false
    depends_on:
      - nats
  uhura-adapter-b:
    image: patonz/uhura:adapter_nats_${TAG}
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    depends_on:
      - uhura-core-b
      - nats
    network_mode: host
    command: "node index.js"
    environment:
      - ID=BETA
      - DEBUG=false




  #clientjs:
  #  build: ./client
  #  network_mode: host
  #  command: "tail -f /dev/null"
  #uhura:
  #  build: 
  #    dockerfile: test.Dockerfile
  #    context: .
  #  volumes:
  #    - 'uhura-volume:/data'
  #  network_mode: host
  #  privileged: true
  #  #command: "tail -f /dev/null"
  #  command: node test.js
    

