version: "2"
volumes:
    uhura-volume:
    fastdds-volume:

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS -c nats-server.conf --cluster nats://0.0.0.0:6222 --http_port 8222"
    volumes:
      - $PWD/nats-server.conf:/nats-server.conf

  uhura_gateway_a:
    #image: patonz/uhura:gateway_${TAG}
    build: 
      context: .
      dockerfile: gateway.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=ALPHA
    depends_on:
      - uhura_adapter_a
      - nats
  uhura_discovery_a:
    #image: patonz/uhura:discovery_${TAG}
    build: 
      context: .
      dockerfile: discovery.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=ALPHA
    depends_on:
      - uhura_gateway_a
      - nats
  uhura_core_a:
    #image: patonz/uhura:core_${TAG}
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
      - DEBUG=false
    depends_on:
      - nats
  uhura_adapter_a:
    #image: patonz/uhura:adapter_nats_${TAG}
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=ALPHA
      - DEBUG=false
    depends_on:
      - uhura_core_a
      - nats



  uhura_gateway_b:
    #image: patonz/uhura:gateway_${TAG}
    build: 
      context: .
      dockerfile: gateway.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=BETA
    depends_on:
      - uhura_adapter_b
      - nats
  uhura_discovery_b:
    #image: patonz/uhura:discovery_${TAG}
    build: 
      context: .
      dockerfile: discovery.Dockerfile
    network_mode: host
    command: "npm run start"
    environment:
      - NATS_SERVER=0.0.0.0:4222
      - UHURA_CORE_ID=BETA
    depends_on:
      - uhura_gateway_b
      - nats
  uhura_core_b:
    #image: patonz/uhura:core_${TAG}
    build: 
      context: .
      dockerfile: core.Dockerfile
    network_mode: host
    command: "node index.js"
    environment:
      - ID=BETA
      - DEBUG=false
    depends_on:
      - nats
  uhura_adapter_b:
    #image: patonz/uhura:adapter_nats_${TAG}
    build: 
      context: .
      dockerfile: adapter.Dockerfile
    depends_on:
      - uhura_core_b
      - nats
    network_mode: host
    command: "node index.js"
    environment:
      - ID=BETA
      - DEBUG=false




  #clientjs:
  #  build: ./client
  #  network_mode: host
  #  command: "tail -f /dev/null"
  #uhura:
  #  build: 
  #    dockerfile: test.Dockerfile
  #    context: .
  #  volumes:
  #    - 'uhura-volume:/data'
  #  network_mode: host
  #  privileged: true
  #  #command: "tail -f /dev/null"
  #  command: node test.js
    

