# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SendMessage.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'SendMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Message_pb2 as Message__pb2
from . import Node_pb2 as Node__pb2
from . import Adapter_pb2 as Adapter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SendMessage.proto\x12\x05uhura\x1a\rMessage.proto\x1a\nNode.proto\x1a\rAdapter.proto\"\xa4\x01\n\x12SendMessageRequest\x12\x1f\n\x07message\x18\x01 \x01(\x0b\x32\x0e.uhura.Message\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x1b\n\x06sender\x18\x03 \x01(\x0b\x32\x0b.uhura.Node\x12\x1e\n\x06source\x18\x04 \x01(\x0b\x32\x0e.uhura.Adapter\x12\x1e\n\treceivers\x18\x05 \x03(\x0b\x32\x0b.uhura.Nodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SendMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=71
  _globals['_SENDMESSAGEREQUEST']._serialized_end=235
# @@protoc_insertion_point(module_scope)
